/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Pretendard", "sans-serif"],
      },
      colors: {
        "landing-light": "#f1f4fd",
        "landing-bold": "#ecf0fa",
        "background": "#ffffff",
        "gray-100": "#f7f7fa",
        "gray-200": "#e4e5f0",
        "gray-300": "#c6cada",
        "gray-400": "#8f95b2",
        "gray-500": "#474d66",
        "gray-600": "#3b415b",
        "green-50": "#EEF9F6",
        "green-100": "#6cd9bf",
        "green-200": "#4CBFA4",
        "green-300": "#32A68A",
        "red-100": "#fbeded",
        "red-200": "#d14343",
        "purple-100": "#8e66ff",
        "yellow-100": "#fdd181",
        "notice-bg": "#ced8d5",
        "notice-text": "#1b1b1b",
        "notice-gray-1": "#a1a1a1",
        "notice-gray-2": "#a4a1aa",
        "notice-blue": "#0085ff",
        "notice-red": "#ff472e",
      },
      fontSize: {
        "5xl": ["48px", { lineHeight: "46px" }],
        "4xl": ["40px", { lineHeight: "42px" }],
        "3xl": ["32px", { lineHeight: "42px" }],
        "2xl": ["24px", { lineHeight: "32px" }],
        "xl": ["20px", { lineHeight: "32px" }],
        "2lg": ["18px", { lineHeight: "26px" }],
        "lg": ["16px", { lineHeight: "26px" }],
        "md": ["14px", { lineHeight: "24px" }],
        "sm": ["13px", { lineHeight: "22px" }],
        "xs": ["12px", { lineHeight: "18px" }],
      },
    },
  },
  plugins: [],
};
